# Generated by Django 3.1 on 2020-08-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('COD', 'Cash On Delivery'), ('PAYPAL', 'paypal')], max_length=50, verbose_name='Payment Method'),
        ),
    ]
